In [1]:
"""Preprocessing of Bakery Sales Dataset"""

'Preprocessing of Bakery Sales Dataset'

In [2]:
"""Load libraries """
import pandas as pd
from pandas import read_csv
import datetime as dt
import os

In [3]:
#get you the path your working in
#all relative paths start from this folder
os.getcwd()

'/workspaces/savebread'

In [4]:
#read in csv
sales = read_csv("src/data/Bakery_Sales.csv")
#sales.info

In [5]:
#read in csv, needs separation by semicolon to read in
weather = read_csv("src/data/Seoul_weather.csv" , sep=";")

In [6]:
#read in csv, needs separation by semicolon to read in
holidays = read_csv("src/data/public_holidays.csv", sep=";")
#holidays

In [7]:
# Split first column in date and time and add as feature at the end
#dateandtime = sales["datetime"]
#sales[["date", "time"]] = dateandtime.str.split(pat = ' ',  n=1, expand = True)

In [8]:
# add weekday column starting from 0 = Monday to 6 = Sunday 
#sales['weekday'] = pd.to_datetime(sales['date']).apply(lambda x: x.weekday())

In [9]:
#sales.head(10)

In [10]:
#sales.head()

In [11]:
#for sales['date'][0].split('-')[-1] == ()

In [12]:
#sales.info

In [13]:
#df=sales.groupby(by=['date']).sum()
#df.info

In [16]:
#datetime
#day of week
#place
#date
#time
#weekday ~
#sales
#df=sales.groupby(by=['date']).sum()
#sales_bak = sales.drop(['place'], axis=1)
#data.dropna(how='all')

In [29]:
#looking at different ways to get rid of "no a number"-Values
#dropna subset, drops every row where subset-Value is NaN
#dropna(how='all'), drops row if all values are NaN
#dropna(thresh = m), drops row if at least m Values are NaN
#nonan = no not a number (values)
sales_nonan = sales.dropna(subset=['total'])
sales_nonan2 = sales.dropna(how='all')
sales_nonan3 = sales.dropna(thresh=5)
sales_nonan['total'].isna().sum()

0

In [30]:
sales_nonan

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time,weekday
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35,3
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10,3
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49,4
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19,5
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,2020-05-02 11:37,Sat,19500.0,동면,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37,5
2416,2020-05-02 11:39,Sat,19800.0,후평 1동,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39,5
2417,2020-05-02 12:15,Sat,14300.0,효자 2동,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15,5
2418,2020-05-02 13:45,Sat,15000.0,소양동,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45,5
2419,2020-05-02 14:45,Sat,24100.0,효자 1동,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45,5

In [22]:
sales = sales_nonan
sales_nonan

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,2020-05-02 11:37,Sat,19500.0,동면,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2416,2020-05-02 11:39,Sat,19800.0,후평 1동,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2417,2020-05-02 12:15,Sat,14300.0,효자 2동,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2418,2020-05-02 13:45,Sat,15000.0,소양동,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2419,2020-05-02 14:45,Sat,24100.0,효자 1동,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [23]:
# Split first column in date and time and add as feature at the end
dateandtime = sales_nonan["datetime"]
sales_nonan[["date", "time"]] = dateandtime.str.split(pat = ' ',  n=1, expand = True)

In [24]:
# add weekday column starting from 0 = Monday to 6 = Sunday 
sales_nonan['weekday'] = pd.to_datetime(sales_nonan['date']).apply(lambda x: x.weekday())

In [25]:
sales_nonan

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time,weekday
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35,3
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10,3
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49,4
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19,5
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,2020-05-02 11:37,Sat,19500.0,동면,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37,5
2416,2020-05-02 11:39,Sat,19800.0,후평 1동,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39,5
2417,2020-05-02 12:15,Sat,14300.0,효자 2동,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15,5
2418,2020-05-02 13:45,Sat,15000.0,소양동,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45,5
2419,2020-05-02 14:45,Sat,24100.0,효자 1동,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45,5

In [35]:
#remove spaces of names

sales_nonan = sales_nonan.rename(columns = {'day of week':'dayofweek'})

#drop datetime and place, only date is important not datetime

sales_inprogress1 = sales_nonan.drop(['datetime','place'], axis=1)

#sales_nonan = sales_inprogress1.dropna(how='all')
#sales_nonan

In [36]:
#convert time in seconds, so its easier to calculate with it
#and set specific times

time_col = sales_nonan['time']
time_col
#time.strptime('00:00:00,000','%I:%M:%S')
def time_in_secs(timestring):
    pt = dt.datetime.strptime(timestring,'%H:%M')
    total_seconds = pt.minute*60 + pt.hour*3600
    return total_seconds

print(time_in_secs('07:00'))
print(time_in_secs('11:00'))
print(time_in_secs('15:00'))
print(time_in_secs('18:00'))
print(time_in_secs('12:00'))

25200
39600
54000
64800
43200

In [38]:
#set daytime borders

sales_inprogress1['daytime']=time_col
for i in range(len(time_col)):
    if 39600 >= time_in_secs(time_col[i]) >= 25200:
        sales_inprogress1['daytime'][i] = 0
    elif 54000 >= time_in_secs(time_col[i]) > 39600:
        sales_inprogress1['daytime'][i] = 1
    elif 64800 >= time_in_secs(time_col[i]) > 54000:
        sales_inprogress1['daytime'][i] = 2
    else:
        sales_inprogress1['daytime'][i] = 3
    
sales_inprogress1

/tmp/ipykernel_2023/623663147.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 2
/tmp/ipykernel_2023/623663147.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 1
/tmp/ipykernel_2023/623663147.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 3
/tmp/ipykernel_2023/623663147.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 0

,dayofweek,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,...,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time,weekday,daytime
0,Thur,23800.0,1.0,NaN,NaN,1.0,NaN,NaN,3.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35,3,2
1,Thur,15800.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10,3,2
2,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49,4,1
3,Sat,14800.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19,5,1
4,Sat,15600.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,Sat,19500.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37,5,1
2416,Sat,19800.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39,5,1
2417,Sat,14300.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15,5,1
2418,Sat,15000.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45,5,1
2419,Sat,24100.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45,5,1

In [41]:
#looking if there are rows with morning sales or night sales

important_cols = sales_inprogress1[['weekday','daytime']].copy()

m=0
for i in range(len(important_cols['daytime'])):
    if important_cols['daytime'][i]==0:
        print(i)
        m+=1
print(m)

#1713 11:00 0
#837 23:02 3
#1721 22:13 3



sales_inprogress1.loc[1713]

1713
1

dayofweek                    Wed
total                    14500.0
angbutter                    NaN
plain bread                  NaN
jam                          NaN
americano                    NaN
croissant                    1.0
caffe latte                  NaN
tiramisu croissant           1.0
cacao deep                   NaN
pain au chocolat             NaN
almond croissant             1.0
croque monsieur              NaN
mad garlic                   NaN
milk tea                     NaN
gateau chocolat              NaN
pandoro                      NaN
cheese cake                  NaN
lemon ade                    NaN
orange pound                 NaN
wiener                       NaN
vanila latte                 NaN
berry ade                    NaN
tiramisu                     NaN
merinque cookies             NaN
date                  2020-02-19
time                       11:00
weekday                        2
daytime                        0
Name: 1713, dtype: object

In [46]:
sales_inprogress1

,dayofweek,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,...,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time,weekday,daytime
0,Thur,23800.0,1.0,NaN,NaN,1.0,NaN,NaN,3.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35,3,2
1,Thur,15800.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10,3,2
2,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49,4,1
3,Sat,14800.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19,5,1
4,Sat,15600.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,Sat,19500.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37,5,1
2416,Sat,19800.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39,5,1
2417,Sat,14300.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15,5,1
2418,Sat,15000.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45,5,1
2419,Sat,24100.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45,5,1

In [44]:
#dropping the 3 rows with values outside of afternoon/evening
sales_inprogress2 = sales_inprogress1.drop(1713)
sales_inprogress3 = sales_inprogress2.drop(837)
sales_inprogress4 = sales_inprogress3.drop(1721)
#sales_inprogress2.head(838)

In [71]:
#drop unnecessary columns

sales_bproducts = sales_inprogress4.drop(['dayofweek', 'time', 'total'], axis=1) #'daytime' #'weekday'
#sales_inprogress2
sales_bproducts

,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,pain au chocolat,almond croissant,...,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,weekday,daytime
0,1.0,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,3,2
1,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,3,2
2,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,4,1
3,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,5,1
4,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,5,1
2416,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,5,1
2417,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,5,1
2418,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,5,1
2419,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,5,1

In [72]:
#rename weather for case_sensitive name
#date needs to be written exactly the same in every merging dataframe

weather.rename(columns = {'datetime' : 'date'}, inplace = True)
weather

,name,date,temp,sunrise,sunset,conditions,description,icon
0,Seoul,2019-07-11,22.0,2019-07-11T05:19:33,2019-07-11T19:55:03,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain
1,Seoul,2019-07-12,23.8,2019-07-12T05:20:11,2019-07-12T19:54:40,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day
2,Seoul,2019-07-13,25.1,2019-07-13T05:20:50,2019-07-13T19:54:15,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain
3,Seoul,2019-07-14,26.0,2019-07-14T05:21:30,2019-07-14T19:53:48,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day
4,Seoul,2019-07-15,24.3,2019-07-15T05:22:11,2019-07-15T19:53:19,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain
...,...,...,...,...,...,...,...,...
294,Seoul,2020-04-30,16.5,2020-04-30T05:37:52,2020-04-30T19:21:10,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day
295,Seoul,2020-05-01,20.5,2020-05-01T05:36:42,2020-05-01T19:22:05,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day
296,Seoul,2020-05-02,20.8,2020-05-02T05:35:34,2020-05-02T19:22:59,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day
297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,https://weather.visualcrossing.com/VisualCross...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
#rename date because of reasons above
#rename type to get rid of the empty space in the name

holidays.rename(columns = {'Date' : 'date', 'type ': 'type'}, inplace = True)
holidays

          date                           Title              type
0   2019-08-15                  Liberation Day  National holiday
1   2019-09-12                 Chuseok Holiday    Public Holiday
2   2019-09-13                         Chuseok    Public Holiday
3   2019-09-14                 Chuseok Holiday    Public Holiday
4   2019-10-03         National Foundation Day  National holiday
5   2019-10-09        Hangeul Proclamation Day  National holiday
6   2019-12-25                   Christmas Day    Public Holiday
7   2020-01-01                  New Year's Day    Public Holiday
8   2020-01-25                 Seollal Holiday    Public Holiday
9   2020-01-27                 Seollal Holiday    Public Holiday
10  2020-02-14                 Valentine's Day        Observance
11  2020-03-01       Independence Movement Day  National holiday
12  2020-03-20                   March Equinox            Season
13  2020-04-05                       Arbor Day        Observance
14  2020-04-15  National Assembly Election Day    Public Holiday
15  2020-04-30               Buddha's Birthday    Public Holiday
16  2020-05-01                       Labor Day      Bank Holiday
17  2020-05-05                  Children's Day    Public Holiday
18  2020-05-08                    Parents' Day        Observance
19  2020-05-15                   Teacher's Day        Observance

In [74]:
#dummy2_drop = dummy2.drop(['sunrise', 'sunset', 'conditions', 'description', 'Title', 'name', 'total'], axis=1)
#dummy2_drop.rename(columns = {'type ':'type'}, inplace = True)
#dummy2_drop['type'] = dummy2_drop['type'].astype('category').cat.codes
#dummy2_drop

In [77]:
#group after date and daytime and weekday
#sum to summarize all the bakery
#reset_index so date and daytime dont become index_columns
 
main_bakery = sales_bproducts.groupby(['date','daytime','weekday']).sum().reset_index()
main_bakery

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,5.0,2.0,0.0,1.0,1.0,0.0,4.0,...,1.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0
413,2020-04-30,2,3,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
414,2020-05-01,1,4,14.0,3.0,0.0,4.0,4.0,1.0,4.0,...,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0
415,2020-05-01,2,4,1.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
416,2020-05-02,1,5,4.0,1.0,0.0,1.0,1.0,1.0,3.0,...,0.0,0.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0

In [79]:
holidays

          date                           Title              type
0   2019-08-15                  Liberation Day  National holiday
1   2019-09-12                 Chuseok Holiday    Public Holiday
2   2019-09-13                         Chuseok    Public Holiday
3   2019-09-14                 Chuseok Holiday    Public Holiday
4   2019-10-03         National Foundation Day  National holiday
5   2019-10-09        Hangeul Proclamation Day  National holiday
6   2019-12-25                   Christmas Day    Public Holiday
7   2020-01-01                  New Year's Day    Public Holiday
8   2020-01-25                 Seollal Holiday    Public Holiday
9   2020-01-27                 Seollal Holiday    Public Holiday
10  2020-02-14                 Valentine's Day        Observance
11  2020-03-01       Independence Movement Day  National holiday
12  2020-03-20                   March Equinox            Season
13  2020-04-05                       Arbor Day        Observance
14  2020-04-15  National Assembly Election Day    Public Holiday
15  2020-04-30               Buddha's Birthday    Public Holiday
16  2020-05-01                       Labor Day      Bank Holiday
17  2020-05-05                  Children's Day    Public Holiday
18  2020-05-08                    Parents' Day        Observance
19  2020-05-15                   Teacher's Day        Observance

In [80]:
#merge weather and holidays

bakery_finished = pd.merge(main_bakery, weather, on="date", how='left')
bakery_finished2 = pd.merge(bakery_finished, holidays, on="date", how="left")
bakery_finished2

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,merinque cookies,name,temp,sunrise,sunset,conditions,description,icon,Title,type
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,0.0,Seoul,22.0,2019-07-11T05:19:33,2019-07-11T19:55:03,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,NaN,NaN
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,Seoul,23.8,2019-07-12T05:20:11,2019-07-12T19:54:40,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,NaN,NaN
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,Seoul,25.1,2019-07-13T05:20:50,2019-07-13T19:54:15,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,NaN,NaN
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,0.0,Seoul,25.1,2019-07-13T05:20:50,2019-07-13T19:54:15,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,NaN,NaN
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,0.0,Seoul,26.0,2019-07-14T05:21:30,2019-07-14T19:53:48,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,5.0,2.0,0.0,1.0,1.0,0.0,4.0,...,0.0,Seoul,16.5,2020-04-30T05:37:52,2020-04-30T19:21:10,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,Buddha's Birthday,Public Holiday
413,2020-04-30,2,3,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,Seoul,16.5,2020-04-30T05:37:52,2020-04-30T19:21:10,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,Buddha's Birthday,Public Holiday
414,2020-05-01,1,4,14.0,3.0,0.0,4.0,4.0,1.0,4.0,...,1.0,Seoul,20.5,2020-05-01T05:36:42,2020-05-01T19:22:05,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,Labor Day,Bank Holiday
415,2020-05-01,2,4,1.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,Seoul,20.5,2020-05-01T05:36:42,2020-05-01T19:22:05,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,Labor Day,Bank Holiday
416,2020-05-02,1,5,4.0,1.0,0.0,1.0,1.0,1.0,3.0,...,0.0,Seoul,20.8,2020-05-02T05:35:34,2020-05-02T19:22:59,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,NaN,NaN

In [132]:
#drop unncessary columns from weather and holidays

bakery_finished2_dropped = bakery_finished2.drop(['sunrise', 'sunset', 'conditions', 'description', 'Title', 'name'], axis=1)

bakery_finished2_dropped.head(60)

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,temp,icon,type
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,22.0,rain,NaN
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.8,partly-cloudy-day,NaN
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,25.1,rain,NaN
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,25.1,rain,NaN
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,0.0,4.0,0.0,4.0,0.0,0.0,0.0,26.0,partly-cloudy-day,NaN
5,2019-07-14,2,6,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,26.0,partly-cloudy-day,NaN
6,2019-07-15,1,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.3,rain,NaN
7,2019-07-15,2,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,24.3,rain,NaN
8,2019-07-17,1,2,5.0,1.0,2.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,26.0,rain,NaN
9,2019-07-17,2,2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,26.0,rain,NaN
10,2019-07-19,1,4,8.0,0.0,0.0,0.0,19.0,0.0,5.0,...,0.0,2.0,0.0,0.0,1.0,0.0,0.0,28.3,partly-cloudy-day,NaN
11,2019-07-19,2,4,3.0,0.0,0.0,0.0,3.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.3,partly-cloudy-day,NaN
12,2019-07-20,1,5,13.0,0.0,1.0,2.0,5.0,3.0,3.0,...,0.0,3.0,1.0,0.0,0.0,3.0,0.0,28.8,rain,NaN
13,2019-07-21,1,6,10.0,4.0,1.0,3.0,7.0,1.0,2.0,...,0.0,3.0,1.0,1.0,0.0,1.0,0.0,25.7,rain,NaN
14,2019-07-21,2,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.7,rain,NaN
15,2019-07-22,1,0,13.0,0.0,0.0,1.0,4.0,0.0,1.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,27.4,rain,NaN
16,2019-07-22,2,0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,27.4,rain,NaN
17,2019-07-24,1,2,10.0,5.0,0.0,2.0,1.0,0.0,2.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,26.8,rain,NaN
18,2019-07-24,2,2,7.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,26.8,rain,NaN
19,2019-07-25,1,3,14.0,1.0,0.0,2.0,3.0,1.0,2.0,...,0.0,0.0,8.0,1.0,1.0,0.0,0.0,26.7,rain,NaN
20,2019-07-25,2,3,2.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,26.7,rain,NaN
21,2019-07-26,1,4,27.0,10.0,1.0,1.0,15.0,0.0,4.0,...,2.0,7.0,6.0,0.0,1.0,0.0,0.0,25.7,rain,NaN
22,2019-07-27,1,5,10.0,7.0,1.0,1.0,6.0,0.0,1.0,...,2.0,1.0,1.0,2.0,0.0,1.0,0.0,28.4,rain,NaN
23,2019-07-28,1,6,8.0,3.0,1.0,1.0,4.0,0.0,3.0,...,0.0,1.0,2.0,0.0,1.0,0.0,0.0,26.9,rain,NaN
24,2019-07-29,1,0,11.0,1.0,0.0,3.0,7.0,0.0,2.0,...,0.0,5.0,3.0,2.0,0.0,0.0,0.0,28.1,rain,NaN
25,2019-07-31,1,2,14.0,4.0,1.0,5.0,3.0,0.0,2.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26.5,rain,NaN
26,2019-08-01,1,3,13.0,5.0,1.0,0.0,9.0,0.0,4.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,26.9,rain,NaN
27,2019-08-02,1,4,21.0,3.0,0.0,0.0,0.0,1.0,3.0,...,0.0,2.0,2.0,0.0,1.0,0.0,0.0,29.1,rain,NaN
28,2019-08-03,1,5,21.0,5.0,2.0,2.0,8.0,0.0,0.0,...,0.0,3.0,13.0,0.0,0.0,0.0,0.0,29.3,rain,NaN
29,2019-08-03,2,5,6.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.3,rain,NaN
30,2019-08-04,1,6,13.0,7.0,2.0,2.0,6.0,0.0,2.0,...,0.0,4.0,6.0,0.0,0.0,0.0,0.0,28.7,partly-cloudy-day,NaN
31,2019-08-05,1,0,15.0,6.0,3.0,0.0,5.0,3.0,4.0,...,1.0,1.0,8.0,3.0,1.0,0.0,0.0,30.7,rain,NaN
32,2019-08-07,1,2,13.0,5.0,1.0,2.0,7.0,2.0,2.0,...,0.0,2.0,3.0,1.0,0.0,0.0,0.0,27.3,rain,NaN
33,2019-08-08,1,3,18.0,6.0,5.0,2.0,5.0,1.0,4.0,...,0.0,5.0,9.0,2.0,0.0,0.0,0.0,29.1,rain,NaN
34,2019-08-09,1,4,1.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,29.9,rain,NaN
35,2019-08-09,2,4,12.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,29.9,rain,NaN
36,2019-08-10,1,5,25.0,3.0,0.0,1.0,5.0,0.0,6.0,...,0.0,2.0,5.0,1.0,0.0,0.0,0.0,31.2,partly-cloudy-day,NaN
37,2019-08-11,1,6,19.0,4.0,1.0,2.0,4.0,2.0,3.0,...,0.0,3.0,6.0,1.0,1.0,1.0,0.0,30.9,rain,NaN
38,2019-08-12,1,0,12.0,4.0,0.0,3.0,7.0,1.0,1.0,...,0.0,1.0,4.0,1.0,0.0,1.0,0.0,26.7,rain,NaN
39,2019-08-12,2,0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.7,rain,NaN
40,2019-08-14,1,2,19.0,5.0,3.0,3.0,10.0,0.0,1.0,...,1.0,0.0,3.0,1.0,0.0,0.0,0.0,30.2,rain,NaN
41,2019-08-15,1,3,13.0,3.0,0.0,1.0,18.0,1.0,2.0,...,0.0,2.0,1.0,1.0,0.0,0.0,0.0,26.5,rain,National holiday
42,2019-08-16,1,4,7.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,3.0,0.0,1.0,0.0,0.0,26.2,rain,NaN
43,2019-08-17,1,5,14.0,6.0,6.0,3.0,3.0,1.0,6.0,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,25.8,rain,NaN
44,2019-08-18,1,6,16.0,2.0,1.0,2.0,10.0,2.0,4.0,...,0.0,5.0,4.0,3.0,0.0,0.0,0.0,25.3,partly-cloudy-day,NaN
45,2019-08-19,1,0,11.0,5.0,2.0,5.0,1.0,1.0,5.0,...,0.0,4.0,1.0,0.0,0.0,0.0,1.0,25.7,partly-cloudy-day,NaN
46,2019-08-19,2,0,3.0,1.0,1.0,0.0,1.0,0.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,25.7,partly-cloudy-day,NaN
47,2019-08-21,1,2,18.0,6.0,0.0,3.0,8.0,1.0,2.0,...,2.0,3.0,6.0,0.0,1.0,0.0,2.0,27.0,rain,NaN
48,2019-08-22,1,3,14.0,0.0,0.0,0.0,3.0,2.0,3.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,26.7,rain,NaN
49,2019-08-22,2,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,26.7,rain,NaN
50,2019-08-23,1,4,15.0,3.0,0.0,1.0,4.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,26.2,partly-cloudy-day,NaN
51,2019-08-23,2,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26.2,partly-cloudy-day,NaN
52,2019-08-24,1,5,16.0,7.0,0.0,1.0,11.0,2.0,2.0,...,0.0,2.0,5.0,0.0,1.0,0.0,1.0,23.8,partly-cloudy-day,NaN
53,2019-08-25,1,6,19.0,2.0,1.0,1.0,2.0,1.0,3.0,...,0.0,0.0,5.0,1.0,0.0,0.0,0.0,24.4,partly-cloudy-day,NaN
54,2019-08-26,1,0,6.0,1.0,0.0,1.0,2.0,0.0,3.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,26.0,partly-cloudy-day,NaN
55,2019-08-26,2,0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,26.0,partly-cloudy-day,NaN
56,2019-08-28,1,2,13.0,2.0,0.0,2.0,5.0,2.0,3.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,26.0,partly-cloudy-day,NaN
57,2019-08-29,1,3,16.0,4.0,0.0,3.0,4.0,1.0,0.0,...,0.0,1.0,2.0,2.0,2.0,0.0,0.0,23.6,rain,NaN
58,2019-08-29,2,3,2.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,2.0,1.0,0.0,0.0,1.0,23.6,rain,NaN
59,2019-08-30,1,4,19.0,1.0,0.0,2.0,2.0,0.0,0.0,...,0.0,4.0,1.0,1.0,0.0,0.0,0.0,22.8,rain,NaN

In [137]:
#0 = no holiday
#1 = Bank holiday
#2 = National holiday
#3 = Observance
#4 = Public Holiday
#5 = Season

for i in range(len(bakery_finished2_dropped)):
    if bakery_finished2_dropped['type'][i] == "Season":
        print(i)

#bakery_finished2_dropped

347
348

In [143]:
bakery_finished2_dropped.iloc[347]

date                  2020-03-20
daytime                        1
weekday                        4
angbutter                    6.0
plain bread                  3.0
jam                          0.0
americano                    4.0
croissant                    5.0
caffe latte                  0.0
tiramisu croissant           0.0
cacao deep                   1.0
pain au chocolat             4.0
almond croissant             0.0
croque monsieur              0.0
mad garlic                   0.0
milk tea                     0.0
gateau chocolat              0.0
pandoro                      0.0
cheese cake                  0.0
lemon ade                    0.0
orange pound                 3.0
wiener                       0.0
vanila latte                 1.0
berry ade                    0.0
tiramisu                     0.0
merinque cookies             0.0
temp                         8.7
icon                   clear-day
type                      Season
Name: 347, dtype: object

In [83]:
bakery_finished2_dropped.isna().any()

date                  False
daytime               False
weekday               False
angbutter             False
plain bread           False
jam                   False
americano             False
croissant             False
caffe latte           False
tiramisu croissant    False
cacao deep            False
pain au chocolat      False
almond croissant      False
croque monsieur       False
mad garlic            False
milk tea              False
gateau chocolat       False
pandoro               False
cheese cake           False
lemon ade             False
orange pound          False
wiener                False
vanila latte          False
berry ade             False
tiramisu              False
merinque cookies      False
temp                  False
icon                  False
type                   True
dtype: bool

In [112]:
#into catcodes +1 so its from 0 to 6

bakery_finished2_dropped = bakery_finished2.drop(['sunrise', 'sunset', 'conditions', 'description', 'Title', 'name'], axis=1)
dummy = bakery_finished2_dropped
dummy['type'] = dummy['type'].astype('category').cat.codes
dummy['type'] = dummy['type'] + 1
dummy.head(60)

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,temp,icon,type
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,22.0,rain,0
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.8,partly-cloudy-day,0
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,25.1,rain,0
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,25.1,rain,0
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,0.0,4.0,0.0,4.0,0.0,0.0,0.0,26.0,partly-cloudy-day,0
5,2019-07-14,2,6,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,26.0,partly-cloudy-day,0
6,2019-07-15,1,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.3,rain,0
7,2019-07-15,2,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,24.3,rain,0
8,2019-07-17,1,2,5.0,1.0,2.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,26.0,rain,0
9,2019-07-17,2,2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,26.0,rain,0
10,2019-07-19,1,4,8.0,0.0,0.0,0.0,19.0,0.0,5.0,...,0.0,2.0,0.0,0.0,1.0,0.0,0.0,28.3,partly-cloudy-day,0
11,2019-07-19,2,4,3.0,0.0,0.0,0.0,3.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.3,partly-cloudy-day,0
12,2019-07-20,1,5,13.0,0.0,1.0,2.0,5.0,3.0,3.0,...,0.0,3.0,1.0,0.0,0.0,3.0,0.0,28.8,rain,0
13,2019-07-21,1,6,10.0,4.0,1.0,3.0,7.0,1.0,2.0,...,0.0,3.0,1.0,1.0,0.0,1.0,0.0,25.7,rain,0
14,2019-07-21,2,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.7,rain,0
15,2019-07-22,1,0,13.0,0.0,0.0,1.0,4.0,0.0,1.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,27.4,rain,0
16,2019-07-22,2,0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,27.4,rain,0
17,2019-07-24,1,2,10.0,5.0,0.0,2.0,1.0,0.0,2.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,26.8,rain,0
18,2019-07-24,2,2,7.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,26.8,rain,0
19,2019-07-25,1,3,14.0,1.0,0.0,2.0,3.0,1.0,2.0,...,0.0,0.0,8.0,1.0,1.0,0.0,0.0,26.7,rain,0
20,2019-07-25,2,3,2.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,26.7,rain,0
21,2019-07-26,1,4,27.0,10.0,1.0,1.0,15.0,0.0,4.0,...,2.0,7.0,6.0,0.0,1.0,0.0,0.0,25.7,rain,0
22,2019-07-27,1,5,10.0,7.0,1.0,1.0,6.0,0.0,1.0,...,2.0,1.0,1.0,2.0,0.0,1.0,0.0,28.4,rain,0
23,2019-07-28,1,6,8.0,3.0,1.0,1.0,4.0,0.0,3.0,...,0.0,1.0,2.0,0.0,1.0,0.0,0.0,26.9,rain,0
24,2019-07-29,1,0,11.0,1.0,0.0,3.0,7.0,0.0,2.0,...,0.0,5.0,3.0,2.0,0.0,0.0,0.0,28.1,rain,0
25,2019-07-31,1,2,14.0,4.0,1.0,5.0,3.0,0.0,2.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26.5,rain,0
26,2019-08-01,1,3,13.0,5.0,1.0,0.0,9.0,0.0,4.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,26.9,rain,0
27,2019-08-02,1,4,21.0,3.0,0.0,0.0,0.0,1.0,3.0,...,0.0,2.0,2.0,0.0,1.0,0.0,0.0,29.1,rain,0
28,2019-08-03,1,5,21.0,5.0,2.0,2.0,8.0,0.0,0.0,...,0.0,3.0,13.0,0.0,0.0,0.0,0.0,29.3,rain,0
29,2019-08-03,2,5,6.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.3,rain,0
30,2019-08-04,1,6,13.0,7.0,2.0,2.0,6.0,0.0,2.0,...,0.0,4.0,6.0,0.0,0.0,0.0,0.0,28.7,partly-cloudy-day,0
31,2019-08-05,1,0,15.0,6.0,3.0,0.0,5.0,3.0,4.0,...,1.0,1.0,8.0,3.0,1.0,0.0,0.0,30.7,rain,0
32,2019-08-07,1,2,13.0,5.0,1.0,2.0,7.0,2.0,2.0,...,0.0,2.0,3.0,1.0,0.0,0.0,0.0,27.3,rain,0
33,2019-08-08,1,3,18.0,6.0,5.0,2.0,5.0,1.0,4.0,...,0.0,5.0,9.0,2.0,0.0,0.0,0.0,29.1,rain,0
34,2019-08-09,1,4,1.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,29.9,rain,0
35,2019-08-09,2,4,12.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,29.9,rain,0
36,2019-08-10,1,5,25.0,3.0,0.0,1.0,5.0,0.0,6.0,...,0.0,2.0,5.0,1.0,0.0,0.0,0.0,31.2,partly-cloudy-day,0
37,2019-08-11,1,6,19.0,4.0,1.0,2.0,4.0,2.0,3.0,...,0.0,3.0,6.0,1.0,1.0,1.0,0.0,30.9,rain,0
38,2019-08-12,1,0,12.0,4.0,0.0,3.0,7.0,1.0,1.0,...,0.0,1.0,4.0,1.0,0.0,1.0,0.0,26.7,rain,0
39,2019-08-12,2,0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.7,rain,0
40,2019-08-14,1,2,19.0,5.0,3.0,3.0,10.0,0.0,1.0,...,1.0,0.0,3.0,1.0,0.0,0.0,0.0,30.2,rain,0
41,2019-08-15,1,3,13.0,3.0,0.0,1.0,18.0,1.0,2.0,...,0.0,2.0,1.0,1.0,0.0,0.0,0.0,26.5,rain,2
42,2019-08-16,1,4,7.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,3.0,0.0,1.0,0.0,0.0,26.2,rain,0
43,2019-08-17,1,5,14.0,6.0,6.0,3.0,3.0,1.0,6.0,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,25.8,rain,0
44,2019-08-18,1,6,16.0,2.0,1.0,2.0,10.0,2.0,4.0,...,0.0,5.0,4.0,3.0,0.0,0.0,0.0,25.3,partly-cloudy-day,0
45,2019-08-19,1,0,11.0,5.0,2.0,5.0,1.0,1.0,5.0,...,0.0,4.0,1.0,0.0,0.0,0.0,1.0,25.7,partly-cloudy-day,0
46,2019-08-19,2,0,3.0,1.0,1.0,0.0,1.0,0.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,25.7,partly-cloudy-day,0
47,2019-08-21,1,2,18.0,6.0,0.0,3.0,8.0,1.0,2.0,...,2.0,3.0,6.0,0.0,1.0,0.0,2.0,27.0,rain,0
48,2019-08-22,1,3,14.0,0.0,0.0,0.0,3.0,2.0,3.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,26.7,rain,0
49,2019-08-22,2,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,26.7,rain,0
50,2019-08-23,1,4,15.0,3.0,0.0,1.0,4.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,26.2,partly-cloudy-day,0
51,2019-08-23,2,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26.2,partly-cloudy-day,0
52,2019-08-24,1,5,16.0,7.0,0.0,1.0,11.0,2.0,2.0,...,0.0,2.0,5.0,0.0,1.0,0.0,1.0,23.8,partly-cloudy-day,0
53,2019-08-25,1,6,19.0,2.0,1.0,1.0,2.0,1.0,3.0,...,0.0,0.0,5.0,1.0,0.0,0.0,0.0,24.4,partly-cloudy-day,0
54,2019-08-26,1,0,6.0,1.0,0.0,1.0,2.0,0.0,3.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,26.0,partly-cloudy-day,0
55,2019-08-26,2,0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,26.0,partly-cloudy-day,0
56,2019-08-28,1,2,13.0,2.0,0.0,2.0,5.0,2.0,3.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,26.0,partly-cloudy-day,0
57,2019-08-29,1,3,16.0,4.0,0.0,3.0,4.0,1.0,0.0,...,0.0,1.0,2.0,2.0,2.0,0.0,0.0,23.6,rain,0
58,2019-08-29,2,3,2.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,2.0,1.0,0.0,0.0,1.0,23.6,rain,0
59,2019-08-30,1,4,19.0,1.0,0.0,2.0,2.0,0.0,0.0,...,0.0,4.0,1.0,1.0,0.0,0.0,0.0,22.8,rain,0

In [124]:
#0 = clear-day
#1 = partly-cloudy-day
#2 = rain
#3 = snow
#4 = wind

for i in range(len(dummy)):
    if dummy['icon'][i] != "rain" and dummy['icon'][i] != "partly-cloudy-day" and dummy['icon'][i] != "clear-day" and dummy['icon'][i] != "snow" and dummy['icon'][i] != "wind":
        print(i)

dummy.iloc[336]

date                  2020-03-12
daytime                        1
weekday                        3
angbutter                   16.0
plain bread                  7.0
jam                          1.0
americano                    1.0
croissant                    3.0
caffe latte                  2.0
tiramisu croissant           6.0
cacao deep                   0.0
pain au chocolat             5.0
almond croissant             0.0
croque monsieur              0.0
mad garlic                   0.0
milk tea                     0.0
gateau chocolat              1.0
pandoro                      1.0
cheese cake                  0.0
lemon ade                    0.0
orange pound                 4.0
wiener                       1.0
vanila latte                 2.0
berry ade                    0.0
tiramisu                     0.0
merinque cookies             0.0
temp                         6.7
weather                        4
h_type                         0
holiday                        0
Name: 336, dtype: object

In [111]:
dummy

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,temp,weather,h_type,holiday
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,22.0,2,0,0
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23.8,1,0,0
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,25.1,2,0,0
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,25.1,2,0,0
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,4.0,0.0,4.0,0.0,0.0,0.0,26.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,5.0,2.0,0.0,1.0,1.0,0.0,4.0,...,1.0,3.0,0.0,0.0,0.0,0.0,16.5,1,4,1
413,2020-04-30,2,3,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,16.5,1,4,1
414,2020-05-01,1,4,14.0,3.0,0.0,4.0,4.0,1.0,4.0,...,3.0,1.0,0.0,0.0,0.0,1.0,20.5,1,1,1
415,2020-05-01,2,4,1.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.5,1,1,1
416,2020-05-02,1,5,4.0,1.0,0.0,1.0,1.0,1.0,3.0,...,1.0,0.0,1.0,1.0,0.0,0.0,20.8,1,0,0

In [106]:
#make list with 1 if it is a holiday and 0 if it isnt
#add list to dataframe as column

holiday=[]

for i in range(len(dummy)):
    if dummy['type'][i] !=0:
        holiday.append(1)
    else:
        holiday.append(0)

print(len(holiday))

dummy['holiday']=holiday

dummy

417

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,temp,icon,type,holiday
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,22.0,rain,0,0
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23.8,partly-cloudy-day,0,0
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,25.1,rain,0,0
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,25.1,rain,0,0
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,4.0,0.0,4.0,0.0,0.0,0.0,26.0,partly-cloudy-day,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,5.0,2.0,0.0,1.0,1.0,0.0,4.0,...,1.0,3.0,0.0,0.0,0.0,0.0,16.5,partly-cloudy-day,4,1
413,2020-04-30,2,3,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,16.5,partly-cloudy-day,4,1
414,2020-05-01,1,4,14.0,3.0,0.0,4.0,4.0,1.0,4.0,...,3.0,1.0,0.0,0.0,0.0,1.0,20.5,partly-cloudy-day,1,1
415,2020-05-01,2,4,1.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.5,partly-cloudy-day,1,1
416,2020-05-02,1,5,4.0,1.0,0.0,1.0,1.0,1.0,3.0,...,1.0,0.0,1.0,1.0,0.0,0.0,20.8,partly-cloudy-day,0,0

In [107]:
#icons into cat.codes

dummy2 = dummy
dummy2['icon'] = dummy2['icon'].astype('category').cat.codes
dummy2

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,temp,icon,type,holiday
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,22.0,2,0,0
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23.8,1,0,0
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,25.1,2,0,0
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,25.1,2,0,0
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,4.0,0.0,4.0,0.0,0.0,0.0,26.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,5.0,2.0,0.0,1.0,1.0,0.0,4.0,...,1.0,3.0,0.0,0.0,0.0,0.0,16.5,1,4,1
413,2020-04-30,2,3,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,16.5,1,4,1
414,2020-05-01,1,4,14.0,3.0,0.0,4.0,4.0,1.0,4.0,...,3.0,1.0,0.0,0.0,0.0,1.0,20.5,1,1,1
415,2020-05-01,2,4,1.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.5,1,1,1
416,2020-05-02,1,5,4.0,1.0,0.0,1.0,1.0,1.0,3.0,...,1.0,0.0,1.0,1.0,0.0,0.0,20.8,1,0,0

In [120]:
dummy2.iloc[283]

date                  2020-02-05
daytime                        1
weekday                        2
angbutter                   20.0
plain bread                  6.0
jam                          4.0
americano                    2.0
croissant                    2.0
caffe latte                  1.0
tiramisu croissant           7.0
cacao deep                   1.0
pain au chocolat             2.0
almond croissant             2.0
croque monsieur              0.0
mad garlic                   0.0
milk tea                     0.0
gateau chocolat              2.0
pandoro                      3.0
cheese cake                  1.0
lemon ade                    0.0
orange pound                 1.0
wiener                       3.0
vanila latte                 1.0
berry ade                    0.0
tiramisu                     0.0
merinque cookies             0.0
temp                        -7.2
weather                        3
h_type                         0
holiday                        0
Name: 283, dtype: object

In [108]:
dummy3= dummy2
dummy3.rename(columns = {'icon' : 'weather', 'type': 'h_type'}, inplace = True)
dummy3.isna().sum()

date                  0
daytime               0
weekday               0
angbutter             0
plain bread           0
jam                   0
americano             0
croissant             0
caffe latte           0
tiramisu croissant    0
cacao deep            0
pain au chocolat      0
almond croissant      0
croque monsieur       0
mad garlic            0
milk tea              0
gateau chocolat       0
pandoro               0
cheese cake           0
lemon ade             0
orange pound          0
wiener                0
vanila latte          0
berry ade             0
tiramisu              0
merinque cookies      0
temp                  0
weather               0
h_type                0
holiday               0
dtype: int64

In [146]:
backup_dummy = dummy3
backup_dummy

,date,daytime,weekday,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,...,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,temp,weather,h_type,holiday
0,2019-07-11,2,3,2.0,0.0,0.0,1.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,22.0,2,0,0
1,2019-07-12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,23.8,1,0,0
2,2019-07-13,1,5,4.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,25.1,2,0,0
3,2019-07-13,2,5,4.0,2.0,0.0,0.0,0.0,0.0,4.0,...,1.0,0.0,1.0,0.0,0.0,0.0,25.1,2,0,0
4,2019-07-14,1,6,14.0,0.0,1.0,3.0,0.0,1.0,8.0,...,4.0,0.0,4.0,0.0,0.0,0.0,26.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,5.0,2.0,0.0,1.0,1.0,0.0,4.0,...,1.0,3.0,0.0,0.0,0.0,0.0,16.5,1,4,1
413,2020-04-30,2,3,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,16.5,1,4,1
414,2020-05-01,1,4,14.0,3.0,0.0,4.0,4.0,1.0,4.0,...,3.0,1.0,0.0,0.0,0.0,1.0,20.5,1,1,1
415,2020-05-01,2,4,1.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.5,1,1,1
416,2020-05-02,1,5,4.0,1.0,0.0,1.0,1.0,1.0,3.0,...,1.0,0.0,1.0,1.0,0.0,0.0,20.8,1,0,0

In [150]:
temp_col = dummy3['temp']
weather_col = dummy3['weather']
h_type_col = dummy3['h_type']
holiday_col = dummy3['holiday']

In [161]:
dummy4 = dummy3.drop(['temp', 'weather', 'h_type', 'holiday'], axis = 1)
dummy4.insert(3, 'holiday', holiday_col)
dummy4.insert(4, 'h_type', h_type_col)
dummy4.insert(5, 'weather', weather_col)
dummy4.insert(6, 'temp', temp_col)

In [164]:
baker_sales_dataset = dummy4
baker_sales_dataset

,date,daytime,weekday,holiday,h_type,weather,temp,angbutter,plain bread,jam,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
0,2019-07-11,2,3,0,0,2,22.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,2019-07-12,1,4,0,0,1,23.8,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2019-07-13,1,5,0,0,2,25.1,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
3,2019-07-13,2,5,0,0,2,25.1,4.0,2.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,2019-07-14,1,6,0,0,1,26.0,14.0,0.0,1.0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2020-04-30,1,3,1,4,1,16.5,5.0,2.0,0.0,...,1.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0
413,2020-04-30,2,3,1,4,1,16.5,2.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
414,2020-05-01,1,4,1,1,1,20.5,14.0,3.0,0.0,...,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0
415,2020-05-01,2,4,1,1,1,20.5,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
416,2020-05-02,1,5,0,0,1,20.8,4.0,1.0,0.0,...,0.0,0.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0

In [109]:
#code snippets 

#for i in range(len(dummy2)):
 #   if dummy2['date'][i]=="2019-09-12":
  #      print(i)

#dummy2.iloc[518]
#dummy2['date']=="2019-09-12"
#dummy2.head()

#dummy2_drop = dummy2.drop(['sunrise', 'sunset', 'conditions', 'description', 'Title', 'name', 'total'], axis=1)
#dummy2_drop.rename(columns = {'type ':'type'}, inplace = True)
##dummy2_drop['type'] = dummy2_drop['type'].astype('category').cat.codes
#dummy2_drop

#"type" columns with space (at the end)
#print(dummy2_drop.columns.tolist())