In [1]:
"""Preprocessing of Bakery Sales Dataset"""

'Preprocessing of Bakery Sales Dataset'

In [1]:
"""Load libraries """
import pandas as pd
from pandas import read_csv
import datetime as dt

In [2]:
sales = read_csv("data/Bakery_Sales.csv")

sales.info

<bound method DataFrame.info of               datetime day of week    total place  angbutter  plain bread  \
0     2019-07-11 15:35        Thur  23800.0   NaN        1.0          NaN
1     2019-07-11 16:10        Thur  15800.0   NaN        1.0          NaN
2     2019-07-12 11:49         Fri  58000.0   NaN        NaN          NaN
3     2019-07-13 13:19         Sat  14800.0   NaN        1.0          1.0
4     2019-07-13 13:22         Sat  15600.0   NaN        2.0          NaN
...                ...         ...      ...   ...        ...          ...
2649               NaN         NaN      NaN   NaN        NaN          NaN
2650               NaN         NaN      NaN   NaN        NaN          NaN
2651               NaN         NaN      NaN   NaN        NaN          NaN
2652               NaN         NaN      NaN   NaN        NaN          NaN
2653  2020-06-18 14:52         NaN      NaN   NaN        NaN          NaN

      jam  americano  croissant  caffe latte  ...  gateau chocolat  pandoro  \
0     NaN        1.0        NaN          NaN  ...              NaN      NaN
1     NaN        NaN        NaN          NaN  ...              NaN      NaN
2     NaN        NaN        NaN          NaN  ...              NaN      NaN
3     NaN        NaN        NaN          NaN  ...              NaN      NaN
4     NaN        NaN        NaN          NaN  ...              NaN      NaN
...   ...        ...        ...          ...  ...              ...      ...
2649  NaN        NaN        NaN          NaN  ...              NaN      NaN
2650  NaN        NaN        NaN          NaN  ...              NaN      NaN
2651  NaN        NaN        NaN          NaN  ...              NaN      NaN
2652  NaN        NaN        NaN          NaN  ...              NaN      NaN
2653  NaN        NaN        NaN          NaN  ...              NaN      NaN

      cheese cake  lemon ade  orange pound  wiener  vanila latte  berry ade  \
0             NaN        NaN           NaN     NaN           1.0        NaN
1             NaN        NaN           1.0     NaN           NaN        NaN
2             NaN        NaN           NaN     NaN           NaN        NaN
3             NaN        NaN           NaN     NaN           1.0        NaN
4             NaN        NaN           NaN     NaN           NaN        NaN
...           ...        ...           ...     ...           ...        ...
2649          NaN        NaN           NaN     NaN           NaN        NaN
2650          NaN        NaN           NaN     NaN           NaN        NaN
2651          NaN        NaN           NaN     NaN           NaN        NaN
2652          NaN        NaN           NaN     NaN           NaN        NaN
2653          NaN        NaN           NaN     NaN           NaN        NaN

      tiramisu  merinque cookies
0          NaN               NaN
1          NaN               NaN
2          NaN               NaN
3          NaN               NaN
4          NaN               NaN
...        ...               ...
2649       NaN               NaN
2650       NaN               NaN
2651       NaN               NaN
2652       NaN               NaN
2653       NaN               NaN

[2654 rows x 27 columns]>

In [3]:
#sales.info()
#sales.describe()

In [4]:
# Split first column in date and time and add as feature at the end
#dateandtime = sales["datetime"]
#sales[["date", "time"]] = dateandtime.str.split(pat = ' ',  n=1, expand = True)

In [5]:
# add weekday column starting from 0 = Monday to 6 = Sunday 
#sales['weekday'] = pd.to_datetime(sales['date']).apply(lambda x: x.weekday())

In [6]:
#sales.head(10)

In [7]:
#sales.head()

In [8]:
#for sales['date'][0].split('-')[-1] == ()

sales

i=0
for col in sales:
    print(col)
    i+=1
    
print(i)

In [9]:
#sales.info

In [10]:
#df=sales.groupby(by=['date']).sum()
#df.info

i=0
for col in df:
    print(col)
    i+=1
    
print(i)
#25
#place
#datetime
#day of week
#date
#time
#weekday ~

i=0
for col in sales:
    print(col)
    i+=1
    
print(i)

In [11]:
#datetime
#day of week
#place
#date
#time
#weekday ~
#sales
#df=sales.groupby(by=['date']).sum()
#sales_bak = sales.drop(['place'], axis=1)
#data.dropna(how='all')

In [12]:
sales_nonan = sales.dropna(subset=['total'])
sales_nonan2 = sales.dropna(how='all')
sales_nonan3 = sales.dropna(thresh=5)
sales_nonan['total'].isna().sum()

0

In [18]:
sales_nonan

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,2020-05-02 11:37,Sat,19500.0,동면,NaN,NaN,NaN,NaN,NaN,1.0,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37
2416,2020-05-02 11:39,Sat,19800.0,후평 1동,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39
2417,2020-05-02 12:15,Sat,14300.0,효자 2동,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15
2418,2020-05-02 13:45,Sat,15000.0,소양동,NaN,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45
2419,2020-05-02 14:45,Sat,24100.0,효자 1동,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45

In [19]:
sales = sales_nonan
sales_nonan

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,2020-05-02 11:37,Sat,19500.0,동면,NaN,NaN,NaN,NaN,NaN,1.0,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37
2416,2020-05-02 11:39,Sat,19800.0,후평 1동,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39
2417,2020-05-02 12:15,Sat,14300.0,효자 2동,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15
2418,2020-05-02 13:45,Sat,15000.0,소양동,NaN,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45
2419,2020-05-02 14:45,Sat,24100.0,효자 1동,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45

In [20]:
# Split first column in date and time and add as feature at the end
dateandtime = sales_nonan["datetime"]
sales_nonan[["date", "time"]] = dateandtime.str.split(pat = ' ',  n=1, expand = True)

C:\Users\olive\AppData\Local\Temp\ipykernel_1804\3333688445.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_nonan[["date", "time"]] = dateandtime.str.split(pat = ' ',  n=1, expand = True)

In [21]:
# add weekday column starting from 0 = Monday to 6 = Sunday 
sales_nonan['weekday'] = pd.to_datetime(sales_nonan['date']).apply(lambda x: x.weekday())

C:\Users\olive\AppData\Local\Temp\ipykernel_1804\905503324.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_nonan['weekday'] = pd.to_datetime(sales_nonan['date']).apply(lambda x: x.weekday())

In [22]:
sales_nonan

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,time,weekday
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,15:35,3
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,16:10,3
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,11:49,4
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,13:19,5
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,13:22,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,2020-05-02 11:37,Sat,19500.0,동면,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,11:37,5
2416,2020-05-02 11:39,Sat,19800.0,후평 1동,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,11:39,5
2417,2020-05-02 12:15,Sat,14300.0,효자 2동,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,12:15,5
2418,2020-05-02 13:45,Sat,15000.0,소양동,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,13:45,5
2419,2020-05-02 14:45,Sat,24100.0,효자 1동,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,14:45,5

In [44]:
sales_nonan = sales_nonan.rename(columns = {'day of week':'dayofweek'})
sales_inprogress1 = sales_nonan.drop(['datetime','place'], axis=1)

#sales_nonan = sales_inprogress1.dropna(how='all')
#sales_nonan

In [152]:
time_col = sales_nonan['time']
time_col
#time.strptime('00:00:00,000','%I:%M:%S')
def time_in_secs(timestring):
    pt = dt.datetime.strptime(timestring,'%H:%M')
    total_seconds = pt.minute*60 + pt.hour*3600
    return total_seconds

print(time_in_secs('07:00'))
print(time_in_secs('11:00'))
print(time_in_secs('15:00'))
print(time_in_secs('18:00'))
print(time_in_secs('12:00'))

25200
39600
54000
64800
43200

In [95]:
sales_inprogress1['daytime']=time_col
for i in range(len(time_col)):
    if 39600 >= time_in_secs(time_col[i]) >= 25200:
        sales_inprogress1['daytime'][i] = 1
    elif 54000 >= time_in_secs(time_col[i]) > 39600:
        sales_inprogress1['daytime'][i] = 2
    elif 64800 >= time_in_secs(time_col[i]) > 54000:
        sales_inprogress1['daytime'][i] = 3
    else:
        sales_inprogress1['daytime'][i] = 4

C:\Users\olive\AppData\Local\Temp\ipykernel_1804\3894427755.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 3
C:\Users\olive\AppData\Local\Temp\ipykernel_1804\3894427755.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 2
C:\Users\olive\AppData\Local\Temp\ipykernel_1804\3894427755.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 4
C:\Users\olive\AppData\Local\Temp\ipykernel_1804\3894427755.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_inprogress1['daytime'][i] = 1

In [151]:
important_cols = sales_inprogress1[['weekday','daytime']].copy()

m=0
for i in range(len(important_cols['daytime'])):
    if important_cols['daytime'][i]==1:
        print(i)
        m+=1
#print(m)

#1713 11:00 1
#837 23:02 4
#1721 22:13 4



sales_inprogress1.loc[1713]

1713

dayofweek                    Wed
total                    14500.0
angbutter                    NaN
plain bread                  NaN
jam                          NaN
americano                    NaN
croissant                    1.0
caffe latte                  NaN
tiramisu croissant           1.0
cacao deep                   NaN
pain au chocolat             NaN
almond croissant             1.0
croque monsieur              NaN
mad garlic                   NaN
milk tea                     NaN
gateau chocolat              NaN
pandoro                      NaN
cheese cake                  NaN
lemon ade                    NaN
orange pound                 NaN
wiener                       NaN
vanila latte                 NaN
berry ade                    NaN
tiramisu                     NaN
merinque cookies             NaN
date                  2020-02-19
time                       11:00
weekday                        2
daytime                        1
Name: 1713, dtype: object

In [132]:
sales_inprogress2 = sales_inprogress1.drop(837)
sales_inprogress2 = sales_inprogress2.drop(1721)
#sales_inprogress2.head(838)

In [137]:
sales_bproducts = sales_inprogress2.drop(['dayofweek', 'time', 'weekday'], axis=1) #'daytime'
#sales_inprogress2
sales_bproducts

,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,pain au chocolat,...,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,daytime
0,23800.0,1.0,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,3
1,15800.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,3
2,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,2
3,14800.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,2
4,15600.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,19500.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2020-05-02,2
2416,19800.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2020-05-02,2
2417,14300.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,2
2418,15000.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-02,2
2419,24100.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2020-05-02,2

In [144]:
sales_inprogress3=sales_bproducts.groupby(by=['date','daytime']).sum() #date
sales_inprogress3.head(60)
#time_col

                        total  angbutter  plain bread  jam  americano  \
date       daytime
2019-07-11 3          39600.0        2.0          0.0  0.0        1.0
2019-07-12 2          58000.0        0.0          0.0  0.0        0.0
2019-07-13 2          46200.0        4.0          1.0  0.0        0.0
           3          71200.0        4.0          2.0  0.0        0.0
2019-07-14 2         192200.0       14.0          0.0  1.0        3.0
           3          19800.0        1.0          0.0  0.0        0.0
2019-07-15 2          15100.0        2.0          0.0  0.0        0.0
           3          15800.0        1.0          0.0  0.0        0.0
2019-07-17 2          56000.0        5.0          1.0  2.0        0.0
           3          18100.0        1.0          1.0  0.0        0.0
2019-07-19 2         160900.0        8.0          0.0  0.0        0.0
           3          35900.0        3.0          0.0  0.0        0.0
2019-07-20 2         203400.0       13.0          0.0  1.0        2.0
2019-07-21 2         180800.0       10.0          4.0  1.0        3.0
           3          15100.0        1.0          0.0  0.0        0.0
2019-07-22 2         128900.0       13.0          0.0  0.0        1.0
           3          38200.0        2.0          0.0  0.0        0.0
2019-07-24 2         114000.0       10.0          5.0  0.0        2.0
           3          63600.0        7.0          0.0  0.0        0.0
2019-07-25 2         209800.0       14.0          1.0  0.0        2.0
           3          49400.0        2.0          0.0  0.0        1.0
2019-07-26 2        1593100.0       27.0         10.0  1.0        1.0
2019-07-27 2         196000.0       10.0          7.0  1.0        1.0
2019-07-28 2         136900.0        8.0          3.0  1.0        1.0
2019-07-29 2         214600.0       11.0          1.0  0.0        3.0
2019-07-31 2         203900.0       14.0          4.0  1.0        5.0
2019-08-01 2         215200.0       13.0          5.0  1.0        0.0
2019-08-02 2         168000.0       21.0          3.0  0.0        0.0
2019-08-03 2         274700.0       21.0          5.0  2.0        2.0
           3          34300.0        6.0          0.0  1.0        0.0
2019-08-04 2         221200.0       13.0          7.0  2.0        2.0
2019-08-05 2         277300.0       15.0          6.0  3.0        0.0
2019-08-07 2         201000.0       13.0          5.0  1.0        2.0
2019-08-08 2         290300.0       18.0          6.0  5.0        2.0
2019-08-09 2          35600.0        1.0          0.0  0.0        0.0
           3          76900.0       12.0          0.0  0.0        0.0
2019-08-10 2         300600.0       25.0          3.0  0.0        1.0
2019-08-11 2         288200.0       19.0          4.0  1.0        2.0
2019-08-12 2         206200.0       12.0          4.0  0.0        3.0
           3          26000.0        5.0          0.0  0.0        0.0
2019-08-14 2         269500.0       19.0          5.0  3.0        3.0
2019-08-15 2         203000.0       13.0          3.0  0.0        1.0
2019-08-16 2          95900.0        7.0          1.0  0.0        0.0
2019-08-17 2         241700.0       14.0          6.0  6.0        3.0
2019-08-18 2         314800.0       16.0          2.0  1.0        2.0
2019-08-19 2         217100.0       11.0          5.0  2.0        5.0
           3          55700.0        3.0          1.0  1.0        0.0
2019-08-21 2         296700.0       18.0          6.0  0.0        3.0
2019-08-22 2         156700.0       14.0          0.0  0.0        0.0
           3          26000.0        0.0          0.0  0.0        0.0
2019-08-23 2         133800.0       15.0          3.0  0.0        1.0
           3          22000.0        0.0          0.0  0.0        0.0
2019-08-24 2         264200.0       16.0          7.0  0.0        1.0
2019-08-25 2         205000.0       19.0          2.0  1.0        1.0
2019-08-26 2         101300.0        6.0          1.0  0.0        1.0
           3          58400.0        3.0          0.0  0.0        1.0
2019-08-28 2         184900.0       13.0          2.0  0.0        2.0
2019-08-29 2         180800.0       16.0          4.0  0.0        3.0
           3          73400.0        2.0          1.0  1.0        0.0
2019-08-30 2         165700.0       19.0          1.0  0.0        2.0

                    croissant  caffe latte  tiramisu croissant  cacao deep  \
date       daytime
2019-07-11 3              0.0          0.0                 4.0         0.0
2019-07-12 2              0.0          0.0                14.0         0.0
2019-07-13 2              0.0          0.0                 1.0         0.0
           3              0.0          0.0                 4.0         2.0
2019-07-14 2              0.0          1.0                 8.0         4.0
           3              0.0          0.0                 1.0         0.0
2019-07-15 2              0.0          0.0                 0.0         1.0
           3              0.0          0.0                 1.0         0.0
2019-07-17 2              1.0          0.0                 1.0         0.0
           3              0.0          0.0                 0.0         0.0
2019-07-19 2             19.0          0.0                 5.0         0.0
           3              3.0          0.0                 2.0         0.0
2019-07-20 2              5.0          3.0                 3.0         0.0
2019-07-21 2              7.0          1.0                 2.0         0.0
           3              0.0          0.0                 0.0         0.0
2019-07-22 2              4.0          0.0                 1.0         0.0
           3              1.0          1.0                 1.0         0.0
2019-07-24 2              1.0          0.0                 2.0         0.0
           3              0.0          0.0                 1.0         0.0
2019-07-25 2              3.0          1.0                 2.0         0.0
           3              1.0          0.0                 0.0         0.0
2019-07-26 2             15.0          0.0                 4.0         0.0
2019-07-27 2              6.0          0.0                 1.0         0.0
2019-07-28 2              4.0          0.0                 3.0         0.0
2019-07-29 2              7.0          0.0                 2.0         0.0
2019-07-31 2              3.0          0.0                 2.0         0.0
2019-08-01 2              9.0          0.0                 4.0         0.0
2019-08-02 2              0.0          1.0                 3.0         0.0
2019-08-03 2              8.0          0.0                 0.0         0.0
           3              0.0          0.0                 0.0         0.0
2019-08-04 2              6.0          0.0                 2.0         0.0
2019-08-05 2              5.0          3.0                 4.0         0.0
2019-08-07 2              7.0          2.0                 2.0         0.0
2019-08-08 2              5.0          1.0                 4.0         0.0
2019-08-09 2              3.0          0.0                 0.0         0.0
           3              2.0          0.0                 0.0         0.0
2019-08-10 2              5.0          0.0                 6.0         0.0
2019-08-11 2              4.0          2.0                 3.0         0.0
2019-08-12 2              7.0          1.0                 1.0         0.0
           3              0.0          0.0                 0.0         0.0
2019-08-14 2             10.0          0.0                 1.0         1.0
2019-08-15 2             18.0          1.0                 2.0         0.0
2019-08-16 2              1.0          0.0                 1.0         1.0
2019-08-17 2              3.0          1.0                 6.0         1.0
2019-08-18 2             10.0          2.0                 4.0         3.0
2019-08-19 2              1.0          1.0                 5.0         2.0
           3              1.0          0.0                 2.0         0.0
2019-08-21 2              8.0          1.0                 2.0         0.0
2019-08-22 2              3.0          2.0                 3.0         1.0
           3              1.0          0.0                 1.0         0.0
2019-08-23 2              4.0          0.0                 0.0         0.0
           3              1.0          0.0                 0.0         1.0
2019-08-24 2             11.0          2.0                 2.0         2.0
2019-08-25 2              2.0          1.0                 3.0         1.0
2019-08-26 2              2.0          0.0                 3.0         2.0
           3              0.0          0.0                 3.0         2.0
2019-08-28 2              5.0          2.0                 3.0         0.0
2019-08-29 2              4.0          1.0                 0.0         0.0
           3              1.0          0.0                 1.0         1.0
2019-08-30 2              2.0          0.0                 0.0         0.0

                    pain au chocolat  ...  gateau chocolat  pandoro  \
date       daytime                    ...
2019-07-11 3                     0.0  ...              0.0      0.0
2019-07-12 2                     0.0  ...              0.0      0.0
2019-07-13 2                     0.0  ...              0.0      0.0
           3                     0.0  ...              0.0      0.0
2019-07-14 2                     0.0  ...              0.0      0.0
           3                     0.0  ...              0.0      0.0
2019-07-15 2                     0.0  ...              0.0      0.0
           3                     0.0  ...              0.0      0.0
2019-07-17 2                     1.0  ...              1.0      0.0
           3                     0.0  ...              0.0      0.0
2019-07-19 2                     3.0  ...              0.0      0.0
           3                     0.0  ...              0.0      0.0
2019-07-20 2                     7.0  ...              1.0      1.0
2019-07-21 2                     3.0  ...              1.0      0.0
           3                     0.0  ...              1.0      0.0
2019-07-22 2                     4.0  ...              0.0      1.0
           3                     0.0  ...              2.0      0.0
2019-07-24 2                     0.0  ...              0.0      0.0
           3                     1.0  ...              0.0      0.0
2019-07-25 2                     5.0  ...              2.0      3.0
           3                     0.0  ...              1.0      1.0
2019-07-26 2                     8.0  ...              1.0      8.0
2019-07-27 2                     4.0  ...              4.0      3.0
2019-07-28 2                     3.0  ...              0.0      3.0
2019-07-29 2                     4.0  ...              1.0      3.0
2019-07-31 2                     4.0  ...              4.0      4.0
2019-08-01 2                     7.0  ...              1.0      4.0
2019-08-02 2                     1.0  ...              2.0      1.0
2019-08-03 2                     4.0  ...              3.0      0.0
           3                     0.0  ...              0.0      0.0
2019-08-04 2                     5.0  ...              1.0      1.0
2019-08-05 2                     6.0  ...              1.0      3.0
2019-08-07 2                     4.0  ...              2.0      0.0
2019-08-08 2                     3.0  ...              3.0      4.0
2019-08-09 2                     1.0  ...              1.0      0.0
           3                     0.0  ...              1.0      0.0
2019-08-10 2                     7.0  ...              2.0      6.0
2019-08-11 2                     9.0  ...              0.0      6.0
2019-08-12 2                     4.0  ...              2.0      2.0
           3                     0.0  ...              0.0      0.0
2019-08-14 2                     4.0  ...              1.0      4.0
2019-08-15 2                     1.0  ...              2.0      0.0
2019-08-16 2                     1.0  ...              0.0      1.0
2019-08-17 2                     4.0  ...              0.0      2.0
2019-08-18 2                     6.0  ...              0.0      7.0
2019-08-19 2                     2.0  ...              1.0      5.0
           3                     0.0  ...              1.0      0.0
2019-08-21 2                     4.0  ...              1.0      3.0
2019-08-22 2                     4.0  ...              0.0      2.0
           3                     0.0  ...              0.0      1.0
2019-08-23 2                     1.0  ...              1.0      1.0
           3                     1.0  ...              0.0      0.0
2019-08-24 2                     3.0  ...              3.0      1.0
2019-08-25 2                     5.0  ...              1.0      1.0
2019-08-26 2                     1.0  ...              0.0      3.0
           3                     0.0  ...              0.0      0.0
2019-08-28 2                     3.0  ...              0.0      3.0
2019-08-29 2                     1.0  ...              0.0      0.0
           3                     1.0  ...              1.0      2.0
2019-08-30 2                     3.0  ...              0.0      1.0

                    cheese cake  lemon ade  orange pound  wiener  \
date       daytime
2019-07-11 3                0.0        0.0           1.0     0.0
2019-07-12 2                0.0        0.0           0.0     0.0
2019-07-13 2                0.0        0.0           0.0     0.0
           3                0.0        0.0           1.0     0.0
2019-07-14 2                0.0        0.0           4.0     0.0
           3                0.0        0.0           1.0     0.0
2019-07-15 2                0.0        0.0           0.0     0.0
           3                0.0        1.0           0.0     0.0
2019-07-17 2                0.0        0.0           1.0     0.0
           3                0.0        0.0           0.0     0.0
2019-07-19 2                0.0        0.0           2.0     0.0
           3                0.0        0.0           0.0     0.0
2019-07-20 2                0.0        0.0           3.0     1.0
2019-07-21 2                0.0        0.0           3.0     1.0
           3                0.0        0.0           0.0     0.0
2019-07-22 2                0.0        0.0           2.0     0.0
           3                0.0        0.0           0.0     0.0
2019-07-24 2                0.0        0.0           1.0     0.0
           3                0.0        0.0           0.0     2.0
2019-07-25 2                0.0        0.0           0.0     8.0
           3                0.0        0.0           1.0     0.0
2019-07-26 2                0.0        2.0           7.0     6.0
2019-07-27 2                0.0        2.0           1.0     1.0
2019-07-28 2                0.0        0.0           1.0     2.0
2019-07-29 2                0.0        0.0           5.0     3.0
2019-07-31 2                0.0        0.0           0.0     0.0
2019-08-01 2                0.0        0.0           2.0     0.0
2019-08-02 2                0.0        0.0           2.0     2.0
2019-08-03 2                0.0        0.0           3.0    13.0
           3                0.0        0.0           0.0     0.0
2019-08-04 2                0.0        0.0           4.0     6.0
2019-08-05 2                0.0        1.0           1.0     8.0
2019-08-07 2                0.0        0.0           2.0     3.0
2019-08-08 2                0.0        0.0           5.0     9.0
2019-08-09 2                0.0        0.0           1.0     0.0
           3                0.0        0.0           0.0     0.0
2019-08-10 2                0.0        0.0           2.0     5.0
2019-08-11 2                0.0        0.0           3.0     6.0
2019-08-12 2                0.0        0.0           1.0     4.0
           3                0.0        0.0           0.0     0.0
2019-08-14 2                0.0        1.0           0.0     3.0
2019-08-15 2                0.0        0.0           2.0     1.0
2019-08-16 2                0.0        0.0           1.0     3.0
2019-08-17 2                0.0        0.0           2.0     0.0
2019-08-18 2                0.0        0.0           5.0     4.0
2019-08-19 2                0.0        0.0           4.0     1.0
           3                0.0        0.0           1.0     0.0
2019-08-21 2                0.0        2.0           3.0     6.0
2019-08-22 2                0.0        0.0           1.0     0.0
           3                0.0        0.0           1.0     1.0
2019-08-23 2                0.0        0.0           2.0     0.0
           3                0.0        0.0           0.0     0.0
2019-08-24 2                0.0        0.0           2.0     5.0
2019-08-25 2                0.0        0.0           0.0     5.0
2019-08-26 2                0.0        0.0           0.0     3.0
           3                0.0        0.0           1.0     1.0
2019-08-28 2                0.0        0.0           0.0     2.0
2019-08-29 2                0.0        0.0           1.0     2.0
           3                0.0        0.0           1.0     2.0
2019-08-30 2                0.0        0.0           4.0     1.0

                    vanila latte  berry ade  tiramisu  merinque cookies
date       daytime
2019-07-11 3                 1.0        0.0       0.0               0.0
2019-07-12 2                 0.0        0.0       0.0               0.0
2019-07-13 2                 2.0        0.0       0.0               0.0
           3                 1.0        0.0       0.0               0.0
2019-07-14 2                 4.0        0.0       0.0               0.0
           3                 1.0        0.0       0.0               0.0
2019-07-15 2                 0.0        0.0       0.0               0.0
           3                 0.0        0.0       0.0               0.0
2019-07-17 2                 0.0        0.0       0.0               0.0
           3                 0.0        1.0       0.0               0.0
2019-07-19 2                 0.0        1.0       0.0               0.0
           3                 0.0        0.0       0.0               0.0
2019-07-20 2                 0.0        0.0       3.0               0.0
2019-07-21 2                 1.0        0.0       1.0               0.0
           3                 0.0        0.0       0.0               0.0
2019-07-22 2                 0.0        0.0       0.0               0.0
           3                 0.0        1.0       0.0               0.0
2019-07-24 2                 1.0        0.0       0.0               0.0
           3                 0.0        0.0       0.0               0.0
2019-07-25 2                 1.0        1.0       0.0               0.0
           3                 1.0        0.0       0.0               0.0
2019-07-26 2                 0.0        1.0       0.0               0.0
2019-07-27 2                 2.0        0.0       1.0               0.0
2019-07-28 2                 0.0        1.0       0.0               0.0
2019-07-29 2                 2.0        0.0       0.0               0.0
2019-07-31 2                 1.0        0.0       0.0               0.0
2019-08-01 2                 0.0        0.0       0.0               0.0
2019-08-02 2                 0.0        1.0       0.0               0.0
2019-08-03 2                 0.0        0.0       0.0               0.0
           3                 0.0        0.0       0.0               0.0
2019-08-04 2                 0.0        0.0       0.0               0.0
2019-08-05 2                 3.0        1.0       0.0               0.0
2019-08-07 2                 1.0        0.0       0.0               0.0
2019-08-08 2                 2.0        0.0       0.0               0.0
2019-08-09 2                 0.0        0.0       0.0               0.0
           3                 1.0        0.0       0.0               0.0
2019-08-10 2                 1.0        0.0       0.0               0.0
2019-08-11 2                 1.0        1.0       1.0               0.0
2019-08-12 2                 1.0        0.0       1.0               0.0

In [ ]:
sales_inprogress3['time'] = time_col

In [161]:
sales_inprogress3

,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,pain au chocolat,...,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,time
date,,,,,,,,,,,,,,,,,,,,,
2019-07-11,39600.0,2.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN
2019-07-12,58000.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2019-07-13,117400.0,8.0,3.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,NaN
2019-07-14,212000.0,15.0,0.0,1.0,3.0,0.0,1.0,9.0,4.0,0.0,...,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,NaN
2019-07-15,30900.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-29,118100.0,7.0,7.0,0.0,1.0,2.0,0.0,4.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
2020-04-30,134100.0,7.0,3.0,0.0,2.0,1.0,0.0,4.0,2.0,2.0,...,1.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,NaN
2020-05-01,215700.0,15.0,4.0,0.0,4.0,5.0,1.0,6.0,1.0,3.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,NaN
2020-05-02,92700.0,4.0,1.0,0.0,1.0,1.0,1.0,3.0,1.0,2.0,...,0.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,NaN
2020-06-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [139]:




sales_inprogress3=sales_bproducts.groupby(by=['date']).sum()
sales_inprogress3['time'] = time_col

,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,pain au chocolat,...,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,time
date,,,,,,,,,,,,,,,,,,,,,
2019-07-11,39600.0,2.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN
2019-07-12,58000.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2019-07-13,117400.0,8.0,3.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,NaN
2019-07-14,212000.0,15.0,0.0,1.0,3.0,0.0,1.0,9.0,4.0,0.0,...,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,NaN
2019-07-15,30900.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-29,118100.0,7.0,7.0,0.0,1.0,2.0,0.0,4.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
2020-04-30,134100.0,7.0,3.0,0.0,2.0,1.0,0.0,4.0,2.0,2.0,...,1.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,NaN
2020-05-01,215700.0,15.0,4.0,0.0,4.0,5.0,1.0,6.0,1.0,3.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,NaN
2020-05-02,92700.0,4.0,1.0,0.0,1.0,1.0,1.0,3.0,1.0,2.0,...,0.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,NaN
2020-06-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [105]:
df=sales_bproducts.groupby(by=['date']).sum()
df

,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,pain au chocolat,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
date,,,,,,,,,,,,,,,,,,,,,
2019-07-11,39600.0,2.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2019-07-12,58000.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-13,117400.0,8.0,3.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0
2019-07-14,212000.0,15.0,0.0,1.0,3.0,0.0,1.0,9.0,4.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0
2019-07-15,30900.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-29,118100.0,7.0,7.0,0.0,1.0,2.0,0.0,4.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2020-04-30,134100.0,7.0,3.0,0.0,2.0,1.0,0.0,4.0,2.0,2.0,...,1.0,1.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0
2020-05-01,215700.0,15.0,4.0,0.0,4.0,5.0,1.0,6.0,1.0,3.0,...,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0
2020-05-02,92700.0,4.0,1.0,0.0,1.0,1.0,1.0,3.0,1.0,2.0,...,0.0,0.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
2020-06-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [106]:
i=0
for col in df:
    print(col)
    i+=1
    
print(i)
#df['Address'] = address

total
angbutter
plain bread
jam
americano
croissant
caffe latte
tiramisu croissant
cacao deep
pain au chocolat
almond croissant
croque monsieur
mad garlic
milk tea
gateau chocolat
pandoro
cheese cake
lemon ade
orange pound
wiener
vanila latte
berry ade
tiramisu
merinque cookies
24

In [111]:
time_col

,dayofweek,total,angbutter,plain bread,jam,americano,croissant,caffe latte,tiramisu croissant,cacao deep,...,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies,date,weekday
0,Thur,23800.0,1.0,NaN,NaN,1.0,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-11,3.0
1,Thur,15800.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019-07-11,3.0
2,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-12,4.0
3,Sat,14800.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2019-07-13,5.0
4,Sat,15600.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-13,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-06-18,3.0